import test from 'node:test';
import assert from 'node:assert/strict';
import {testModel,auditLabel} from '../src/model-audit.mjs';
import {visibleMessage} from '../src/transcript-memory.mjs';
const model={id:'fixture',tools:true},u={id:'up',kind:'fixture'};
function service({failTool=false}={}){return {config:{value:{upstreams:[u],routes:[]}},platforms:{models:async()=>[model],async chat(t,r){let delta={content:r.messages.some(m=>m.role==='tool')?'5':'AUDIT_OK'};if(r.tool_choice?.function){delta=failTool?{content:'no tool'}:{tool_calls:[{index:0,id:'call1',type:'function',function:{name:'audit_add',arguments:'{"a":2,"b":3}'}}]};}const stop=delta.tool_calls?'tool_calls':'stop';return {response:new Response('data: '+JSON.stringify({choices:[{index:0,delta,finish_reason:null}]})+'\n\ndata: '+JSON.stringify({choices:[{index:0,delta:{},finish_reason:stop}]})+'\n\ndata: [DONE]\n\n',{headers:{'Content-Type':'text/event-stream'}})};}}};}
test('audit checks ordinary, SSE, tools and local result roundtrip without modifying routes',async()=>{const s=service(),r=await testModel(s,u,model);assert.equal(r.status,'passed');assert.deepEqual(r.tests.map(t=>t.stage),['ordinary','stream','tools','roundtrip']);assert.ok(r.tests.every(t=>t.ok));assert.deepEqual(s.config.value.routes,[]);});
test('audit marks failed structured tools separately from successful chat',async()=>{const r=await testModel(service({failTool:true}),u,model);assert.equal(r.status,'partial');assert.equal(r.tests[2].ok,false);assert.equal(r.tests[3].status,'skipped');assert.match(auditLabel(r),/工具未通过/);});
test('unavailable transport is explicitly labeled and never secretly substitutes models',async()=>{const r=await testModel({config:{}},u,{id:'missing',callable:false,unavailableReason:'missing wire'});assert.equal(r.status,'unavailable');assert.equal(r.tests.length,0);assert.equal(auditLabel(r),'当前通道未提供');});
test('upstream auth rejection is a definitive failed audit, not transient uncertainty',async()=>{const s=service();s.platforms.chat=async()=>{const e=Error('auth fixture');e.status=401;e.code='authentication';throw e;};assert.equal((await testModel(s,u,model)).status,'failed');});
test('memory archives visible messages but excludes hidden analysis and tool output',()=>{const row={type:'response_item',payload:{type:'message',role:'assistant',channel:'final',content:[{type:'output_text',text:'visible fixture'}]}};assert.match(visibleMessage(row),/visible fixture/);assert.equal(visibleMessage({...row,payload:{...row.payload,channel:'analysis'}}),undefined);assert.equal(visibleMessage({type:'response_item',payload:{type:'function_call_output',output:'secret fixture'}}),undefined);});
