import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const memory=await mkdtemp(join(tmpdir(),'scoped-audit-'));process.env.AI_CREDIT_MEMORY=memory;
const {startModelAudit,importedTargets}=await import('../src/model-audit.mjs');
const {startServer}=await import('../src/server.mjs');
const {validateConfig}=await import('../src/config.mjs');
function fixture(limit=67108864){let record;return {config:{value:{server:{host:'127.0.0.1',port:0,bodyLimitBytes:limit},accounts:[{id:'a',enabled:true}],upstreams:[{id:'up',kind:'workbuddy',accountId:'a'}],routes:[{id:'enabled',targets:[{upstreamId:'up',model:'good'}]},{id:'duplicate',targets:[{upstreamId:'up',model:'good'}]},{id:'hidden',enabled:false,targets:[{upstreamId:'up',model:'other'}]}]}},keys:{apiKey:'fixture-api',adminKey:'fixture-admin'},ledger:{get:()=>record,set:(_k,v)=>{record=structuredClone(v)}},platforms:{models:async()=>[{id:'good',tools:true},{id:'other',tools:true}],async chat(_t,r){const delta=r.tool_choice?.function?{tool_calls:[{index:0,id:'call',type:'function',function:{name:'audit_add',arguments:'{"a":2,"b":3}'}}]}:{content:r.messages.some(m=>m.role==='tool')?'5':'AUDIT_OK'};return {response:new Response('data: '+JSON.stringify({choices:[{index:0,delta,finish_reason:null}]})+'\n\ndata: '+JSON.stringify({choices:[{index:0,delta:{},finish_reason:delta.tool_calls?'tool_calls':'stop'}]})+'\n\ndata: [DONE]\n\n',{headers:{'Content-Type':'text/event-stream'}})};}},router:{async *chat(r){yield {choices:[{index:0,delta:{content:'KEPT:'+Buffer.byteLength(JSON.stringify(r))},finish_reason:'stop'}]};}}};}
const headers={authorization:'Bearer fixture-api','content-type':'application/json'};
test('old-session 5 MiB history and tool results traverse both public and DSH-private HTTP without trimming',async()=>{
 const s=fixture(),body={model:'enabled',messages:[{role:'system',content:'system preserved'},{role:'user',content:'历史'.repeat(900000)},{role:'assistant',content:null,tool_calls:[{id:'c',type:'function',function:{name:'read',arguments:'{}'}}]},{role:'tool',tool_call_id:'c',content:'old tool result'},{role:'user',content:'continue'}]};let received;
 s.router.chat=async function*(r){received=r;yield {choices:[{index:0,delta:{content:'FULL_HISTORY_OK'},finish_reason:'stop'}]};};
 for(const admin of [true,false]){const rt=await startServer(s,{admin});try{const r=await fetch(rt.baseUrl+'/v1/chat/completions',{method:'POST',headers,body:JSON.stringify(body)});assert.equal(r.status,200);assert.equal((await r.json()).choices[0].message.content,'FULL_HISTORY_OK');assert.deepEqual(received,body);if(!admin)assert.equal((await fetch(rt.baseUrl+'/admin/config',{headers:{authorization:'Bearer fixture-admin'}})).status,404);}finally{await rt.close();}}
});
test('body policy reload works without HTTP server restart and still rejects explicitly over-limit requests',async()=>{
 const s=fixture(4194304),rt=await startServer(s),body=JSON.stringify({model:'enabled',messages:[{role:'user',content:'x'.repeat(5*1024*1024)}]});
 try{let r=await fetch(rt.baseUrl+'/v1/chat/completions',{method:'POST',headers,body});assert.equal(r.status,413);assert.match((await r.json()).error.message,/4194304 bytes/);s.config.value={...s.config.value,server:{...s.config.value.server,bodyLimitBytes:67108864}};r=await fetch(rt.baseUrl+'/v1/chat/completions',{method:'POST',headers,body});assert.equal(r.status,200);s.config.value.server.bodyLimitBytes=1024;r=await fetch(rt.baseUrl+'/v1/chat/completions',{method:'POST',headers,body});assert.equal(r.status,413);}finally{await rt.close();}
});
test('chunked UTF-8 input is measured as bytes and receives a JSON 413, not a destroyed socket',async()=>{
 const rt=await startServer(fixture(1024));try{const result=await new Promise((resolve,reject)=>{const req=http.request(rt.baseUrl+'/v1/chat/completions',{method:'POST',headers},res=>{let body='';res.on('data',c=>body+=c);res.on('end',()=>resolve({status:res.statusCode,body}));});req.on('error',reject);req.write('{"model":"enabled","messages":[{"role":"user","content":"');req.write('汉'.repeat(500));req.end('"}]}');});assert.equal(result.status,413);assert.equal(JSON.parse(result.body).error.code,'body_too_large');}finally{await rt.close();}
});
test('request limits are bounded and config default is 64 MiB',async()=>{const c=JSON.parse(await readFile(new URL('../config.example.json',import.meta.url)));assert.equal(c.server.bodyLimitBytes,67108864);for(const bad of [0,-1,Infinity,67108865,'67108864',1024.5]){assert.throws(()=>validateConfig({...c,server:{...c.server,bodyLimitBytes:bad}}),/bodyLimitBytes/);}assert.ok(validateConfig({...c,server:{...c.server,bodyLimitBytes:2048}}));});
test('imported audit refreshes catalogs, runs all four stages once per target, preserves unrelated results and route choices',async()=>{
 const s=fixture(),before=structuredClone(s.config.value.routes),prior={upstreamId:'up',model:'other',status:'passed',finishedAt:'old',tests:[]};s.ledger.set('model-audit',{results:[prior]});let fetches=0,calls=0;const models=s.platforms.models,chat=s.platforms.chat;s.platforms.models=async(id,opts)=>{if(opts?.refresh){fetches++;assert.equal(id,'up');}return models();};s.platforms.chat=async(...a)=>{calls++;return chat(...a);};
 const r=startModelAudit(s,{scope:'imported'});assert.equal(r.total,1);assert.equal(r.results.find(x=>x.model==='good').status,'running');await s.auditPromise;const done=s.ledger.get();assert.equal(done.scope,'imported');assert.equal(done.completed,1);assert.equal(done.status,'completed');assert.equal(calls,4);assert.equal(fetches,1);assert.equal(done.results.find(x=>x.model==='good').status,'passed');assert.deepEqual(done.results.find(x=>x.model==='other'),prior);assert.deepEqual(s.config.value.routes,before);
});
test('imported audit includes fallback and WorkBuddy pool accounts but excludes disabled routes',()=>{const s=fixture();s.config.value.routes[0].targets.push({upstreamId:'backup',model:'good'});assert.deepEqual(importedTargets(s).map(r=>r.upstreamId),['up','backup']);s.router.pool={candidates:()=>[{upstreamId:'pool-b',model:'good'},{upstreamId:'up',model:'good'}]};assert.deepEqual(importedTargets(s).map(r=>r.upstreamId),['pool-b','up']);});
test('a failed directory marks exact selected model, never substitutes a different model',async()=>{const s=fixture();s.platforms.models=async()=>{throw Error('directory fixture unavailable');};startModelAudit(s,{scope:'imported'});await s.auditPromise;const r=s.ledger.get();assert.equal(r.completed,1);assert.equal(r.results[0].model,'good');assert.equal(r.results[0].status,'uncertain');assert.match(r.results[0].reason,/directory fixture/);});
test('audit repeated clicks share one run; different scope is queued without overlapping tests',async()=>{
 const s=fixture();let release,active=0,max=0;const gate=new Promise(r=>release=r),chat=s.platforms.chat;s.platforms.chat=async(...args)=>{active++;max=Math.max(max,active);await gate;try{return await chat(...args);}finally{active--;}};
 const all=startModelAudit(s);const promise=s.auditPromise;assert.equal(startModelAudit(s),all);const queued=startModelAudit(s,{scope:'imported'});assert.equal(queued.queuedScope,'imported');assert.equal(s.auditPromise,promise);release();await promise;while(s.auditPromise)await s.auditPromise;assert.equal(s.ledger.get().scope,'imported');assert.equal(s.ledger.get().total,1);assert.ok(max<=2);
});
test('scoped audit HTTP returns 202 promptly and GET reports completed four-stage results',async()=>{const s=fixture(),rt=await startServer(s);try{const r=await fetch(rt.baseUrl+'/admin/model-tests',{method:'POST',headers:{authorization:'Bearer fixture-admin','content-type':'application/json'},body:'{"scope":"imported"}'});assert.equal(r.status,202);assert.equal((await r.json()).scope,'imported');await s.auditPromise;const done=await(await fetch(rt.baseUrl+'/admin/model-tests',{headers:{authorization:'Bearer fixture-admin'}})).json();assert.equal(done.results[0].tests.length,4);assert.equal(done.summary.passed,1);const bad=await fetch(rt.baseUrl+'/admin/model-tests',{method:'POST',headers:{authorization:'Bearer fixture-admin'},body:'{"scope":"invalid"}'});assert.equal(bad.status,400);}finally{await rt.close();}});
test('empty imported selection is completed with zero calls and unrelated history intact',async()=>{const s=fixture();s.config.value.routes.forEach(r=>r.enabled=false);s.ledger.set('model-audit',{results:[{upstreamId:'old',model:'old',status:'passed'}]});s.platforms.models=async()=>{throw Error('should not fetch');};startModelAudit(s,{scope:'imported'});await s.auditPromise;assert.equal(s.ledger.get().completed,0);assert.equal(s.ledger.get().total,0);assert.equal(s.ledger.get().results[0].status,'passed');});
test('legacy POST with no body retains all-model audit compatibility',async()=>{const s=fixture(),rt=await startServer(s);try{const r=await fetch(rt.baseUrl+'/admin/model-tests',{method:'POST',headers:{authorization:'Bearer fixture-admin'}});assert.equal(r.status,202);assert.equal((await r.json()).scope,'all');await s.auditPromise;}finally{await rt.close();}});
test.after(async()=>{await rm(memory,{recursive:true,force:true});});
