import test from 'node:test';
import assert from 'node:assert/strict';
import {modelDirectory,importModels} from '../src/model-directory.mjs';
import {qwenBody,qwenCosy} from '../src/qwenwork-models.mjs';
import {zcodeBody} from '../src/zcode-models.mjs';
function fixture(){const config={value:{upstreams:[{id:'w',kind:'workbuddy'},{id:'q',kind:'qwenwork'},{id:'z',kind:'zcode'}],routes:[{id:'legacy',targets:[{upstreamId:'w',model:'a'}]}]},async save(v){this.value=v;this.saves=(this.saves??0)+1;}};return {config,platforms:{async models(id){if(id==='z')throw Error('upstream not ready');return [{id:'a',name:'A',tools:true,multimodal:false},{id:'b',name:'B',tools:false,multimodal:true}];}},router:{async models(){return {data:[{id:'legacy'}]};}}};}
test('full model directory separates discovered/imported and retains provider errors',async()=>{const s=fixture(),d=await modelDirectory(s);assert.equal(d.count,4);assert.equal(d.published,1);assert.equal(d.providers[0].models[0].imported,true);assert.equal(d.providers[1].models[0].imported,false);assert.ok(d.providers[2].error);assert.equal(d.providers[0].models[1].multimodal,true);});
test('selected import preserves prior routes, is idempotent and supports deselection',async()=>{const s=fixture(),item={upstreamId:'q',model:'b'};await importModels(s,[item]);await importModels(s,[item]);assert.equal(s.config.value.routes.length,2);assert.equal(s.config.value.routes[0].id,'legacy');await importModels(s,[{...item,enabled:false}]);assert.equal(s.config.value.routes[1].enabled,false);await importModels(s,[{...item,enabled:true}]);assert.equal(s.config.value.routes[1].enabled,true);});
test('failed batch import never saves partial selection',async()=>{const s=fixture();await assert.rejects(importModels(s,[{upstreamId:'q',model:'b'},{upstreamId:'w',model:'absent'}]));assert.equal(s.config.value.routes.length,1);assert.equal(s.config.saves,undefined);await assert.rejects(importModels(s,[]));});
test('Qwen native body preserves tool arguments and tool results',()=>{const messages=[{role:'user',content:'Add numbers'},{role:'assistant',tool_calls:[{id:'call1',function:{name:'sum',arguments:'{"a":17,"b":25}'}}]},{role:'tool',tool_call_id:'call1',content:'42'}];const tools=[{type:'function',function:{name:'sum'}}];const b=qwenBody({model:'flash',messages,tools,max_tokens:2048});assert.deepEqual(b.messages,messages);assert.deepEqual(b.tools,tools);assert.equal(b.model_config.key,'flash');assert.equal(b.parameters.max_tokens,2048);});
test('Qwen COSY header encrypts credential and signs body',()=>{const h=qwenCosy({principal:'test-user',accessToken:'fixture-private-token'},'https://gateway.qwenwork.cn/api/v2/model/list');assert.match(h.Authorization,/^Bearer COSY\./);assert.equal(h['Cosy-User'],'test-user');assert.ok(h['Cosy-Key']);assert.ok(!JSON.stringify(h).includes('fixture-private-token'));});
test('ZCode client context keeps caller system and local tool definitions',()=>{const b=zcodeBody({model:'glm-5.3-flash',messages:[{role:'system',content:'CALLER_SYSTEM'},{role:'user',content:'Add'}],tools:[{type:'function',function:{name:'sum',parameters:{type:'object'}}}]});assert.equal(b.system.length,4);assert.equal(b.system[3].text,'CALLER_SYSTEM');assert.match(b.system[0].text,/ZCode/);assert.equal(b.messages.at(-1).content[0].text,'Add');assert.equal(b.tools[0].name,'sum');});
