import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,readFile,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {createService} from '../src/service.mjs';import {startServer} from '../src/server.mjs';import {AppError} from '../src/util.mjs';
test('authenticated pool HTTP: A depleted -> B ordinary/SSE/tools; manual switch and admin isolation',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'wb-http-'));let s,h;try{
  const c=JSON.parse(await readFile(new URL('../config.example.json',import.meta.url)));c.dataDir=join(dir,'data');c.server.port=0;c.accounts=['a','b'].map(id=>({id,platform:'workbuddy',enabled:true,credentials:{kind:'file',file:join(dir,id+'.json')},tasks:[{id:'daily-checkin',enabled:true}]}));c.upstreams=['a','b'].map(id=>({id:'u'+id,kind:'workbuddy',accountId:id,enabled:true}));c.routes=[{id:'r',targets:[{upstreamId:'ua',model:'m'}],enabled:true}];const f=join(dir,'config.json');await writeFile(f,JSON.stringify(c));s=await createService(f);let calls=[];
  s.platforms.models=async()=>[{id:'m',name:'M',tools:true,multimodal:true}];s.platforms.chat=async(t,q)=>{calls.push(t.upstreamId);if(t.upstreamId==='ua')throw new AppError('insufficient credits',402,'quota');const message=q.tools?.length?{role:'assistant',content:null,tool_calls:[{id:'call1',type:'function',function:{name:'sum',arguments:'{"a":2,"b":3}'}}]}:{role:'assistant',content:'B_OK'};return {response:new Response(JSON.stringify({choices:[{message,finish_reason:q.tools?.length?'tool_calls':'stop'}]}),{headers:{'Content-Type':'application/json'}})}};
  h=await startServer(s,{port:0});const request=async(path,body,key=s.keys.adminKey)=>{const r=await fetch(h.baseUrl+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return r;};
  assert.equal((await request('/admin/workbuddy/pool',{routeId:'r',accountIds:['a','b']},s.keys.apiKey)).status,401);
  assert.equal((await request('/admin/workbuddy/pool',{routeId:'r',accountIds:['a','b']})).status,200);
  const msg={model:'r',messages:[{role:'user',content:'hello'}]};let r=await request('/v1/chat/completions',msg,s.keys.apiKey);assert.equal(r.status,200);assert.equal((await r.json()).choices[0].message.content,'B_OK');assert.deepEqual(calls,['ua','ub']);
  r=await request('/v1/chat/completions',{...msg,stream:true,tools:[{type:'function',function:{name:'sum',parameters:{type:'object',properties:{a:{type:'number'},b:{type:'number'}}}}}]},s.keys.apiKey);const text=await r.text();assert.equal(r.status,200);assert.match(text,/tool_calls/);assert.match(text,/sum/);assert.match(text,/\[DONE\]/);assert.equal(calls.at(-1),'ub');
  assert.equal((await request('/admin/workbuddy/switch',{routeId:'r',accountId:'a'})).status,409);s.router.pool.revive('a');assert.equal((await request('/admin/workbuddy/switch',{routeId:'r',accountId:'a'})).status,200);
  const state=await (await request('/admin/workbuddy/pools')).json();assert.equal(state.routes[0].preferredAccountId,'a');
 }finally{await h?.close();await s?.close();await rm(dir,{recursive:true,force:true,maxRetries:5});}
});
