import {zcodeBalance} from './zcode.mjs';
import {errorView} from './util.mjs';
export async function boundedBalanceRead(work,timeoutMs=25000){let timer;try{return await Promise.race([Promise.resolve().then(work),new Promise((_,reject)=>{timer=setTimeout(()=>{const e=new Error('余额查询超时，请稍后重新核验');e.code='balance_timeout';reject(e);},timeoutMs)})]);}finally{clearTimeout(timer);}}
const num=x=>x!==null&&x!==undefined&&Number.isFinite(Number(x))?Number(x):null;
export function normalizeBalance(platform,h){
 let value=null,unit='积分',parts=[],expiresAt=null,checkedIn=false,note='';
 if(platform==='workbuddy'){value=num(h.credits.total);parts=h.credits.packages.map(p=>({name:p.packageName,value:p.remain,expiresAt:p.expiresAtMs?new Date(p.expiresAtMs).toISOString():null}));checkedIn=h.checkin.todayCheckedIn;note='连续签到 '+h.checkin.streakDays+' 天 · 今日 '+h.checkin.todayCredit+' 积分';}
 if(platform==='trae'){const s=h.snapshot.summary;value=Math.round((s.totalAmount-s.consumedAmount)*100)/100;checkedIn=h.checkin.checkedIn;note='总额度 '+s.totalAmount+' · 已使用 '+s.consumedAmount;}
 if(platform==='qwenwork'){value=num(h.quota?.remaining??h.wallets?.dailyBalance+h.wallets?.monthlyBalance+h.wallets?.longtermBalance);const w=h.wallets;parts=[{name:'每日额度',value:w.dailyBalance},{name:'月度额度',value:w.monthlyBalance},{name:'活动余额',value:w.longtermBalance}];checkedIn=true;note='个人版每日额度由服务端自动刷新，无需签到';expiresAt=w.activeWallets?.find(w=>w.balance===h.wallets.dailyBalance)?.validTo;}
 if(platform==='minimax'){const s=h.membership.op_credit_summary;value=num(s?.total_remaining_amount);parts=[{name:'免费余额',value:num(s?.free_remaining_amount)},{name:'购买余额',value:num(s?.purchased_remaining_amount)}];checkedIn=h.checkin.claimed;note='今日奖励 '+h.checkin.credits+' 积分（含连签奖励，不重复相加）';}
 if(platform==='antigravity'){value=null;unit='模型配额';note='本机协议桥已连接；上游未提供统一积分余额，模型可用性以实际调用为准';}
 if(platform==='bigmodel'){value=num(h.cash?.availableBalance);unit='元';parts=h.packages??[];checkedIn=false;note=h.packagesError?h.packagesError.message:'现金与资源包分开 · '+parts.length+' 个资源包，Token / 次数见额度明细';}
 if(platform==='zcode'){if(!Array.isArray(h.balance?.balances))throw new Error('ZCode balance response missing balances array');unit='Token';const buckets=(h.balance?.balances??[]).filter(b=>!b.expires_at||b.expires_at*1000>Date.now());parts=buckets.map(b=>({name:b.show_name??b.entitlement_id,value:num(b.available_units??b.remaining_units),expiresAt:b.expires_at?new Date(b.expires_at*1000).toISOString():null}));value=parts.length?parts.reduce((sum,p)=>sum+p.value,0):0;expiresAt=parts.map(p=>p.expiresAt).filter(Boolean).sort()[0]??null;checkedIn=(h.balance?.plans??[]).length>0;note='按可领取套餐核验；Token 与积分分开显示';}
 expiresAt??=parts.map(p=>p.expiresAt).filter(Boolean).sort()[0]??null;
 return {value,unit,parts,expiresAt,checkedIn,note,...(platform==='bigmodel'?{packagesError:h.packagesError,cashError:h.cashError}: {})};
}
export async function balances(service,{refresh=false}={}){service.balanceCache??=new Map();return {accounts:await Promise.all(service.config.value.accounts.map(async a=>{let old=service.balanceCache.get(a.id);if(!refresh&&old&&Date.now()-Date.parse(old.checkedAt)<60000)return old;try{const h=await boundedBalanceRead(async()=>{const h=await service.platforms.health(a.id);if(a.platform==='zcode')h.balance=await zcodeBalance(await service.credentials.resolve(a.id));return h;},service.balanceTimeoutMs??25000);const row={accountId:a.id,label:a.label??a.id,platform:a.platform,enabled:a.enabled!==false,...normalizeBalance(a.platform,h),checkedAt:new Date().toISOString(),stale:false};service.balanceCache.set(a.id,row);try{service.ledger?.observeBalance?.(row)}catch(e){console.error('balance_observation_write_failed',e.code??'storage_error');}if(refresh&&a.platform==='workbuddy'&&row.value>0)service.router.pool?.revive(a.id);return row;}catch(e){return {...(old??{accountId:a.id,label:a.label??a.id,platform:a.platform,value:null,unit:a.platform==='zcode'?'Token':'积分',parts:[]}),stale:!!old,error:errorView(e),enabled:a.enabled!==false};}}))};}
